In [5]:
import numpy as np
print(np.__version__)

1.26.4


In [6]:
#creating Array

arr = np.array([[1,3,4,5,6],[2,1,3,1,4]])
print(arr)

[[1 3 4 5 6]
 [2 1 3 1 4]]


In [7]:
print(arr.ndim)

2


In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [11]:
arr = np.array([1,2,3,4,5])

In [14]:
print(arr[1]+arr[3])

6


In [16]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])

2
